### ISSUE TITLE
[BUG] Unable to connect to OpenStack cluster

### ISSUE THREAD

**Issue by tarach** [opensearch-project/logstash-output-opensearch#103]
**Command:**
```docker run -it --rm --name logstash opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.2 -e "$(cat logstash.conf)"```

**logstash.conf:**
```
input {
    stdin { }
}
output {
    opensearch {
        hosts => [
            "https://<domain>.eu-central-1.es.amazonaws.com:443"
        ]
        index => "opensearch-logstash-docker-%{+YYYY.MM.dd}"
        user => "<username>"
        password => "<password>"
        ssl => true
        ssl_certificate_verification => false
   }
}
```
**Console output:**
```
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
[2021-12-05T20:17:08,407][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
[2021-12-05T20:17:08,429][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.13.2", "jruby.version"=>"jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +indy +jit [linux-x86_64]"}
[2021-12-05T20:17:08,485][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
[2021-12-05T20:17:08,580][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
[2021-12-05T20:17:09,576][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-12-05T20:17:09,628][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"fb6b7526-a889-435f-9348-45aad8f6e6a2", :path=>"/usr/share/logstash/data/uuid"}
[2021-12-05T20:17:11,346][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-12-05T20:17:12,471][INFO ][org.reflections.Reflections] Reflections took 118 ms to scan 1 urls, producing 24 keys and 48 values
[2021-12-05T20:17:13,525][WARN ][deprecation.logstash.inputs.stdin] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
[2021-12-05T20:17:13,711][WARN ][deprecation.logstash.outputs.opensearch] Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.
[2021-12-05T20:17:13,783][INFO ][logstash.outputs.opensearch][main] New OpenSearch output {:class=>"LogStash::Outputs::OpenSearch", :hosts=>["https://<domain>.eu-central-1.es.amazonaws.com:443"]}
[2021-12-05T20:17:13,816][WARN ][logstash.outputs.opensearch][main] ** WARNING ** Detected UNSAFE options in opensearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2021-12-05T20:17:14,474][INFO ][logstash.outputs.opensearch][main] OpenSearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/]}}
[2021-12-05T20:17:15,504][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:15,645][INFO ][logstash.outputs.opensearch][main] Cluster version determined (7.10.2) {:version=>7}
[2021-12-05T20:17:15,678][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:15,776][ERROR][logstash.outputs.opensearch][main] Unable to retrieve OpenSearch cluster uuid {:message=>"No Available connections", :exception=>LogStash::Outputs::OpenSearch::HttpClient::Pool::NoConnectionAvailableError, :backtrace=>["/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:349:in `with_connection'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:260:in `perform_request'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:268:in `block in get'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client.rb:208:in `get'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/plugin_mixins/opensearch/common.rb:90:in `discover_cluster_uuid'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch.rb:247:in `finish_register'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch.rb:225:in `block in register'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}
[2021-12-05T20:17:15,794][INFO ][logstash.outputs.opensearch][main] Using a default mapping template {:version=>7, :ecs_compatibility=>:disabled}
[2021-12-05T20:17:15,844][ERROR][logstash.outputs.opensearch][main] Failed to install template {:message=>"No Available connections", :exception=>LogStash::Outputs::OpenSearch::HttpClient::Pool::NoConnectionAvailableError, :backtrace=>["/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:349:in `with_connection'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:260:in `perform_request'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client/pool.rb:268:in `block in Pool'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client.rb:388:in `exists?'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client.rb:393:in `template_exists?'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/http_client.rb:89:in `template_install'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch.rb:413:in `install_template'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch.rb:248:in `finish_register'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/outputs/opensearch.rb:225:in `block in register'", "/usr/share/logstash/vendor/local_gems/217134f0/logstash-output-opensearch/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}
[2021-12-05T20:17:15,850][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>250, "pipeline.sources"=>["config string"], :thread=>"#<Thread:0x1e7f4d48 run>"}
[2021-12-05T20:17:17,295][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.44}
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jrubystdinchannel.StdinChannelLibrary$Reader (file:/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jruby-stdin-channel-0.2.0-java/lib/jruby_stdin_channel/jruby_stdin_channel.jar) to field java.io.FilterInputStream.in
WARNING: Please consider reporting this to the maintainers of com.jrubystdinchannel.StdinChannelLibrary$Reader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2021-12-05T20:17:17,335][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
The stdin plugin is now waiting for input:
[2021-12-05T20:17:17,522][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2021-12-05T20:17:20,747][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:20,812][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:25,835][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:25,894][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:30,916][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:30,960][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:35,988][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:36,026][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:41,061][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:41,111][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:46,137][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:46,171][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:51,197][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:51,229][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:17:56,249][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:17:56,285][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:18:01,307][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:18:01,346][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
[2021-12-05T20:18:06,367][WARN ][logstash.outputs.opensearch][main] Restored connection to OpenSearch instance {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/"}
[2021-12-05T20:18:06,402][ERROR][logstash.outputs.opensearch][main] Could not connect to cluster {:url=>"https://<username>:xxxxxx@<domain>.eu-central-1.es.amazonaws.com:443/", :distribution=>nil, :major_version=>7}
^C[2021-12-05T20:18:08,060][WARN ][logstash.runner          ] SIGINT received. Shutting down.
[2021-12-05T20:18:08,428][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2021-12-05T20:18:09,370][INFO ][logstash.runner          ] Logstash shut down.
```

Connecting from either my local browser as well as via links terminal browser produces results similar to this one:
{
  "name": "<xxxxxxxxxxxxxxxx>",
  "cluster_name": "<aws id>:<username>",
  "cluster_uuid": "<yyyyy>",
  "version": {
    "number": "7.10.2",
    "build_type": "tar",
    "build_hash": "unknown",
    "build_date": "2021-09-21T11:27:10.894287Z",
    "build_snapshot": false,
    "lucene_version": "8.8.2",
    "minimum_wire_compatibility_version": "6.8.0",
    "minimum_index_compatibility_version": "6.0.0-beta1"
  },
  "tagline": "The OpenSearch Project: https://opensearch.org/"
}

**Comment by tarach** [comment]
In version 7.13.4 this issue does not exists. Works fine. Only 7.13.2 version of the docker image is affected.
