### ISSUE TITLE
[BUG] logstash-oss-with-opensearch-output-plugin:8.4.0 crashes while using lumberjack over tls

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/logstash-output-opensearch#194]
**Describe the bug**
Using docker container logstash-oss-with-opensearch-output-plugin:8.4.0

config:

```
input {
  udp {
    port => 5245
    codec => cef {
        # delimiter => "\r\n"
        ecs_compatibility => v8
    }
  }
}

output {
        lumberjack {
                codec => json
                hosts => "server"
                ssl_certificate => "/etc/logstash/lumberjack.cert"
                port => 5003
        }
	stdout {}
}
```

```
xdr-logstash-f5-waf-1      | Feb 12, 2023 12:06:16 AM jnr.netdb.NativeProtocolsDB load
xdr-logstash-f5-waf-1      | WARNING: Failed to load native protocols db
xdr-logstash-f5-waf-1      | java.lang.RuntimeException: getprotobyname_r failed
xdr-logstash-f5-waf-1      | 	at jnr.netdb.NativeProtocolsDB$LinuxNativeProtocolsDB.getProtocolByName(NativeProtocolsDB.java:180)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.NativeProtocolsDB.load(NativeProtocolsDB.java:80)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.NativeProtocolsDB.access$000(NativeProtocolsDB.java:40)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.NativeProtocolsDB$SingletonHolder.<clinit>(NativeProtocolsDB.java:47)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.NativeProtocolsDB.getInstance(NativeProtocolsDB.java:43)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.Protocol$ProtocolDBSingletonHolder.load(Protocol.java:107)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.Protocol$ProtocolDBSingletonHolder.<clinit>(Protocol.java:103)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.Protocol.getProtocolDB(Protocol.java:96)
xdr-logstash-f5-waf-1      | 	at jnr.netdb.Protocol.getProtocolByNumber(Protocol.java:59)
xdr-logstash-f5-waf-1      | 	at org.jruby.ext.socket.Addrinfo.<init>(Addrinfo.java:847)
xdr-logstash-f5-waf-1      | 	at org.jruby.ext.socket.SocketUtils.ip_address_list(SocketUtils.java:434)
xdr-logstash-f5-waf-1      | 	at org.jruby.ext.socket.RubySocket.ip_address_list(RubySocket.java:342)
xdr-logstash-f5-waf-1      | 	at org.jruby.ext.socket.RubySocket$INVOKER$s$0$0$ip_address_list.call(RubySocket$INVOKER$s$0$0$ip_address_list.gen)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:840)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$use_ipv6?$0(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:418)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$use_ipv6?$0$__VARARGS__(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:416)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$each_address$0(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:411)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$each_address$0$__VARARGS__(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:409)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$block$each_address$1(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:122)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.Block.yield(Block.java:188)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray.each(RubyArray.java:1865)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$each_address$0(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:121)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$each_address$0$__VARARGS__(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:115)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$getaddresses$0(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:108)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$getaddresses$0$__VARARGS__(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:106)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$getaddresses$0(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:57)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.jruby.lib.ruby.stdlib.resolv.RUBY$method$getaddresses$0$__VARARGS__(/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/resolv.rb:56)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_output_minus_lumberjack_minus_3_dot_1_dot_9.lib.logstash.outputs.lumberjack.RUBY$block$connect$1(/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:84)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.Block.yield(Block.java:188)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray.each(RubyArray.java:1865)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_output_minus_lumberjack_minus_3_dot_1_dot_9.lib.logstash.outputs.lumberjack.RUBY$method$connect$0(/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:84)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_output_minus_lumberjack_minus_3_dot_1_dot_9.lib.logstash.outputs.lumberjack.RUBY$method$connect$0$__VARARGS__(/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:78)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_output_minus_lumberjack_minus_3_dot_1_dot_9.lib.logstash.outputs.lumberjack.RUBY$method$register$0(/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:49)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:152)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:148)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyClass.finvoke(RubyClass.java:570)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.Helpers.invoke(Helpers.java:649)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:348)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.lambda$reg$1(OutputStrategyExt.java:236)
xdr-logstash-f5-waf-1      | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.OutputStrategyExt$LegacyOutputStrategyExt.reg(OutputStrategyExt.java:236)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.register(OutputStrategyExt.java:131)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.OutputDelegatorExt.doRegister(OutputDelegatorExt.java:117)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.register(AbstractOutputDelegatorExt.java:68)
xdr-logstash-f5-waf-1      | 	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt$INVOKER$i$0$0$register.call(AbstractOutputDelegatorExt$INVOKER$i$0$0$register.gen)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:840)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$register_plugins$1(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:233)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:151)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.BlockBody.yield(BlockBody.java:106)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.Block.yield(Block.java:188)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray.each(RubyArray.java:1865)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:560)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:198)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$register_plugins$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$register_plugins$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:230)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$maybe_setup_out_plugins$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:598)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$maybe_setup_out_plugins$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:596)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$start_workers$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:245)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$start_workers$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:241)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$run$0(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:190)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$run$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:139)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:112)
xdr-logstash-f5-waf-1      | 	at org.jruby.ir.targets.indy.InvokeSite.invoke(InvokeSite.java:208)
xdr-logstash-f5-waf-1      | 	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start$1(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:142)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:141)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:64)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)
xdr-logstash-f5-waf-1      | 	at org.jruby.runtime.Block.call(Block.java:143)
xdr-logstash-f5-waf-1      | 	at org.jruby.RubyProc.call(RubyProc.java:309)
xdr-logstash-f5-waf-1      | 	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:107)
xdr-logstash-f5-waf-1      | 	at java.base/java.lang.Thread.run(Thread.java:833)
xdr-logstash-f5-waf-1      |
xdr-logstash-f5-waf-1      | [2023-02-12T00:06:16,533][ERROR][logstash.outputs.lumberjack][main] All hosts unavailable, sleeping {:hosts=>[], :e=>#<RuntimeError: Could not connect to any hosts>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:31:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:24:in `initialize'", "org/jruby/RubyClass.java:909:in `new'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:85:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-output-lumberjack-3.1.9/lib/logstash/outputs/lumberjack.rb:49:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:233:in `block in register_plugins'", "org/jruby/RubyArray.java:1865:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:598:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:245:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:190:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:142:in `block in start'"]}
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
```

**Expected behavior**
Not crash

**Plugins**
Default docker container

**Screenshots**

**Host/Environment (please complete the following information):**
Host RHEL7 with docker

**Additional context**

**Comment by ict-one-nl** [comment]
Possible solution: https://github.com/jruby/jruby/issues/3955#issuecomment-254504589

**Comment by asifsmohammed** [comment]
Hi @ict-one-nl thanks for your interest in the logstash-output-opensearch plugin. Looks like your'e using having issue with lumberjack plugin. [logstash-output-opensearch](https://github.com/opensearch-project/logstash-output-opensearch) plugin only supports distribution of openSearch plugin.

**Comment by ict-one-nl** [comment]
Thanks. Who maintains the docker container from the opensearch project then?

**Comment by dlvenable** [comment]
> Thanks. Who maintains the docker container from the opensearch project then?

@ict-one-nl , This Docker container currently comes from this project.

The Docker container is not a custom build of Logstash. Rather, it is the Logstash Docker image with OpenSearch plugins installed.

So this is likely a bug in Logstash or one of the Logstash plugins you are using, perhaps the Lumberjack plugin. Those are different projects and you may wish to seek help on them from the maintainers of those projects.

**Comment by ict-one-nl** [comment]
thanks for the extensive answer, will try to debug.
