### ISSUE TITLE
Unable to create template on open search 1.3 getting 400 error 

### ISSUE THREAD

**Issue by gaddehyd** [opensearch-project/logstash-output-opensearch#249]
Unable create template on open search 1.3 version using logstash 8.13.2 version.
Getting below error, Opensearch is hosted on aws. 

[Ruby-0-Thread-10: /usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/plugin_mixins/opensearch/common.rb:77] 
opensearch - Failed to install template {:message=>"Got response code '400' contacting OpenSearch at URL 'https://xxxx:443/_template/logstash'", 
:exception=>LogStash::Outputs::OpenSearch::HttpClient::Pool::BadResponseCodeError, 
:backtrace=>["/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:181:in 
`perform_request'", "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/pool.rb:272:in `perform_request_to_url'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/pool.rb:259:in `block in perform_request'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/pool.rb:348:in `with_connection'",
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/pool.rb:258:in `perform_request'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client/pool.rb:266:in `block in Pool'",
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client.rb:404:in `template_put'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/http_client.rb:82:in `template_install'",
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", 
"/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'",
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch.rb:419:in `install_template'", 
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch.rb:254:in `finish_register'", 
 "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/outputs/opensearch.rb:231:in `block in register'",
  "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-opensearch-2.0.2-java/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}

**Comment by dblock** [comment]
This is similar to https://github.com/opensearch-project/logstash-output-opensearch/issues/227 and possibly others. The generic 400 error is unfortunately not helpful. Is there more in the output? Enable `--debug`, can we get the body of the error?

I opened https://github.com/opensearch-project/logstash-output-opensearch/issues/251, maybe you/someone can help improve this?

**Comment by gaddehyd** [comment]
@dblock It's a odd behaviour  for my case, after adding `--debug` I am able to create template but with `logstash -f file_name ` getting 400 error

**Comment by dblock** [comment]
@gaddehyd that would definitely be a bug! maybe some code that only gets executed on debug? what are the versions that you're using? post relevant logs with and without?

**Comment by gaddehyd** [comment]
[logstash-with-debug.txt](https://github.com/opensearch-project/logstash-output-opensearch/files/15105243/logstash-with-debug.txt)
[logstash-without-debug.txt](https://github.com/opensearch-project/logstash-output-opensearch/files/15105244/logstash-without-debug.txt)
@dblock I tried on logstash 8.13.2 and 7.15.0 versions and Open Search plugin 2.0.2

**Comment by dblock** [comment]
Thanks. This has to be a red herring and a timing problem where by enabling debug logs we end up doing something out of order. There's nothing I found in the logs out of ordinary.

Are you able to build the plugin code here and make some changes? I would make a change in https://github.com/opensearch-project/logstash-output-opensearch/blob/f45b8c753ac4366e91194c682c85ced3858c9792/lib/logstash/outputs/opensearch/http_client/pool.rb#L26 to display the body of the error to start.

**Comment by gaddehyd** [comment]
[2024-04-29T05:59:12,764][ERROR][logstash.outputs.opensearch][main] Failed to install template {:message=>"Got response code '400' contacting OpenSearch at URL 'https://url:443/_template/template_toptracks_stats'", :exception=>LogStash::Outputs::OpenSearch::HttpClient::Pool::BadResponseCodeError, :backtrace=>["/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:181:in `perform_request'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:272:in `perform_request_to_url'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:259:in `block in perform_request'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:348:in `with_connection'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:258:in `perform_request'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:266:in `block in Pool'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client.rb:404:in `template_put'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client.rb:82:in `template_install'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:419:in `install_template'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:254:in `finish_register'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:231:in `block in register'", "/usr/share/logstash/vendor/local_gems/c5127f68/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}

@dblock Again same error, I have build the plugin and deployed on logstash. I am running image on AWS Batch service.

**Comment by dblock** [comment]
@gaddehyd the code should be modified to display the `@response_body`, this message is unfortunately not helpful

**Comment by gaddehyd** [comment]
@dblock Can you suggest where I need to update the code for response_body ?

**Comment by dblock** [comment]
Here: https://github.com/opensearch-project/logstash-output-opensearch/blob/f45b8c753ac4366e91194c682c85ced3858c9792/lib/logstash/outputs/opensearch/http_client/pool.rb#L26C86-L27C10

It says

```
"Got response code '#{response_code}' contacting OpenSearch at URL '#{@url}'"
```

try changing it to 

```
"Got response code '#{response_code}' contacting OpenSearch at URL '#{@url}, request: #{@request_body}, response: #{@response_body}'"
```

**Comment by gaddehyd** [comment]
@dblock I have updated code and tried. 
[2024-05-01T22:16:54,994][ERROR][logstash.outputs.opensearch][main] Failed to install template {:message=>"Got response code '400' contacting OpenSearch at URL 'https://****.us-west-2.es.amazonaws.com:443/_template/template_toptracks_stats, request: {\"version\":60002,\"settings\":{\"index\":{\"number_of_shards\":\"1\",\"refresh_interval\":\"5s\"}},\"template\":\"Feld-type mapping for cassandra\",\"index_patterns\":[\"logstash-***-cassandra-202112\"],\"mappings\":{\"properties\":{\"country_id as country\":{\"type\":\"varchar\"},\"fiscal_period_end as fiscal_period\":{\"type\":\"int\"},\"period_type\":{\"type\":\"varchar\"},\"bucket_number\":{\"type\":\"int\"},\"stg_exec_id\":{\"type\":\"bigint\"},\"territory\":{\"type\":\"varchar\"},\"status\":{\"type\":\"smallint\"},\"track_dsp_id as adam_id\":{\"type\":\"bigint\"},\"blobAsText(textAsBlob('Latin_America')) as region\":{\"type\":\"varchar\"},\"blobAsText(textAsBlob('Bahamas')) as country_name\":{\"type\":\"varchar\"},\"composer_author\":{\"type\":\"varchar\"},\"album_title as album\":{\"type\":\"varchar\"},\"track_isrc as isrc\":{\"type\":\"varchar\"},\"iswc\":{\"type\":\"varchar\"},\"track_title as track_name\":{\"type\":\"varchar\"},\"transaction_id\":{\"type\":\"varchar\"},\"carrier_2_cnt as  ***_Carrier_Trial_2\":{\"type\":\"bigint\"},\"individual_paid_3or4_bundle_cnt as  ***_Individual_3or4Services\":{\"type\":\"bigint\"},\"family_paid_3or4_bundle_cnt as  ***_Family_3or4Services\":{\"type\":\"bigint\"},\"family_paid_5ormore_bundle_cnt as  ***_Family_5orMoreServices\":{\"type\":\"bigint\"},\"mma_trial_1st_month_unit_cnt as  MMA_Trial_1stMonth\":{\"type\":\"bigint\"},\"mma_trial_inv_2nd_3rd_month_unit_cnt as  MMA_Trial_Individual_2nd3rdMonth\":{\"type\":\"bigint\"},\"mma_trial_fam_2nd_3rd_month_unit_cnt as  MMA_Trial_Family_2nd3rdMonth\":{\"type\":\"bigint\"},\"mma_trial_stu_2nd_3rd_month_unit_cnt as  MMA_Trial_Student_2nd3rdMonth\":{\"type\":\"bigint\"},\"individual_plan_unit_count as  ***_Individual_Monthly\":{\"type\":\"bigint\"},\"family_plan_unit_count as  ***_Family_Monthly\":{\"type\":\"bigint\"},\"trial_period_unit_count as  ***_Trial\":{\"type\":\"bigint\"},\"carrier_1_cnt as  ***_Carrier_Trial_1\":{\"type\":\"bigint\"},\"direct_student_paid_unit_cnt as  ***_Student\":{\"type\":\"bigint\"},\"carrier_3_cnt as  ***_Carrier_Trial_3\":{\"type\":\"bigint\"},\"carrier_4_cnt as  ***_Carrier_Paid\":{\"type\":\"bigint\"},\"individual_annual_plan_cnt as  ***_Individual_Annual\":{\"type\":\"bigint\"},\"lyrics_cnt as  ***_Lyrics\":{\"type\":\"bigint\"},\"mch_paid_unit_cnt as  Music_Subscription_Match\":{\"type\":\"bigint\"},\"carrier_5_cnt as  ***_Carrier_Trial_5\":{\"type\":\"bigint\"},\"winbacks_3_month_disc_ind_cnt as  ***_3For1_Winback_Individual\":{\"type\":\"bigint\"},\"winbacks_3_month_fam_cnt as  ***_3For1_Winback_Family\":{\"type\":\"bigint\"},\"tsl_count as  ***_Lyrics_TimeSynced \":{\"type\":\"bigint\"},\"trial_6m_first_3m_unit_cnt as  ***_6MTrial_FirstHalf\":{\"type\":\"bigint\"},\"trial_6m_last_3m_unit_cnt as  ***_6MTrial_SecondHalf\":{\"type\":\"bigint\"},\"blobasbigint(bigintasblob(000000000000000)) as ***_Individual_6M_Hardware_Bundle\":{\"type\":\"bigint\"},\"blobasbigint(bigintasblob(000000000000000)) as ***_Individual_Glide\":{\"type\":\"bigint\"},\"blobasbigint(bigintasblob(000000000000000)) as ***_IntroPricing\":{\"type\":\"bigint\"},\"blobasbigint(bigintasblob(000000000000000)) as ***_Carrier_Paid_Family\":{\"type\":\"bigint\"},\"@timestamp\":{\"type\":\"date\"},\"@version\":{\"type\":\"keyword\"}}}}, response: {\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"No handler for type [varchar] declared on field [album_title as album]\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"Failed to parse mapping [_doc]: No handler for type [varchar] declared on field [album_title as album]\",\"caused_by\":{\"type\":\"mapper_parsing_exception\",\"reason\":\"No handler for type [varchar] declared on field [album_title as album]\"}},\"status\":400}'", :exception=>LogStash::Outputs::OpenSearch::HttpClient::Pool::BadResponseCodeError, :backtrace=>["/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/manticore_adapter.rb:181:in `perform_request'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:273:in `perform_request_to_url'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:260:in `block in perform_request'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:349:in `with_connection'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:259:in `perform_request'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client/pool.rb:267:in `block in Pool'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client.rb:404:in `template_put'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/http_client.rb:82:in `template_install'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/template_manager.rb:37:in `install'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch/template_manager.rb:25:in `install_template'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:419:in `install_template'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:254:in `finish_register'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/outputs/opensearch.rb:231:in `block in register'", "/usr/share/logstash/vendor/local_gems/d54fe7d7/logstash-output-opensearch-2.0.2-universal.arm64e-darwin-23/lib/logstash/plugin_mixins/opensearch/common.rb:83:in `block in after_successful_connection'"]}

**Comment by gaddehyd** [comment]
@dblock I have updated my index template with open search supported data types, But we getting new issue after updating the template.
`response: {\"error\":{\"root_cause\":[{\"type\":\"not_x_content_exception\",\"reason\":\"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}],\"type\":\"not_x_content_exception\",\"reason\":\"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"},\"status\":500}'"  `

**Comment by dblock** [comment]
I still would like a detailed repro so that we can actually improve the code to show the error here. Help us build one? Something super rudimentary with 5 steps from scratch would be amazing.

> I have updated my index template with open search supported data types(https://opensearch.org/docs/latest/search-plugins/sql/datatypes/)

Good. This is one less problem. Could you please give a tl;dr on exactly what you had and did for the next person after you have repro steps? 

> Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes

Where's this error from? Same place? I am not familiar with this error, but there's a lot of google hits that say something about the data format being the problem / json being sent with the wrong content type, etc.
